name: CCache example

on: push

jobs:
  ccache-example:
    runs-on: macos-14
    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Maestro
        run: "export MAESTRO_VERSION={1.36.0}; curl -Ls 'https://get.maestro.mobile.dev' | bash && brew tap facebook/fb && brew install facebook/fb/idb-companion"

      - name: Set Mastro path
        run: |
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Cache yarn packages
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-packages-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-packages-
            

      - name: install dependencies
        run: yarn

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: install pods
        run: cd ios && pod install --repo-update

      - name: Cache Xcode Derived Data
        uses: irgaly/xcode-cache@v1
        with:
          key: ${{ runner.os }}-xcode-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-xcode-


      - name: run iOS simulator
        run: |
          sed -i -e 's/ONLY_ACTIVE_ARCH = NO;/ONLY_ACTIVE_ARCH = YES;/g' ./ios/MaestroCache.xcodeproj/project.pbxproj
          npx react-native run-ios --simulator="iPhone 15 Pro" --mode=Release


      - name: run Maestro
        run: maestro test ./maestro/test.yaml
        continue-on-error: true
