name: CCache example

on: push

jobs:
  ccache-example:
    runs-on: macos-13
    env: 
      DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Run xcode-select
        run: sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: Install Maestro
        run: "export MAESTRO_VERSION={1.36.0}; curl -Ls 'https://get.maestro.mobile.dev' | bash && brew tap facebook/fb && brew install facebook/fb/idb-companion"

      - name: Set Mastro path
        run: |
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Cache yarn packages
        id: cache_yarn
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-packages-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-packages-v2-
            

      - name: install dependencies
        if: steps.cache_yarn.outputs.cache-hit != 'true'
        run: yarn

      - name: Restore Pods cache
        uses: actions/cache@v4
        id: cache_pods
        with:
          path: |
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
            **/ios/Pods
          key: ${{ runner.os }}-pods-v3-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-v3-

      - name: Cache ios build
        uses: actions/cache@v4
        id: cache_build
        with:
          path: |
            **/ios/build
          key: ${{ runner.os }}-build-v1-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-b1

      - name: install pods
        if: steps.cache_pods.outputs.cache-hit != 'true'
        run: cd ios && pod install --repo-update


      - name: run iOS simulator
        run: |
          sed -i -e 's/ONLY_ACTIVE_ARCH = NO;/ONLY_ACTIVE_ARCH = YES;/g' ./ios/MaestroCache.xcodeproj/project.pbxproj
          npx react-native run-ios --simulator="iPhone 14 Pro (16.4)" --mode=Release


      - name: run Maestro
        run: maestro test ./maestro/test.yaml
        continue-on-error: true
