name: CCache example

on: push

jobs:
  ccache-example:
    runs-on: macos-13
    env: 
      DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Run xcode-select
        run: sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: Cache yarn packages
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-packages-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-packages-
            

      - name: install dependencies
        run: yarn

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: install pods
        run: cd ios && pod install --repo-update

      - name: Cache Xcode Dervied Data
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-xcode-

      - name: run iOS simulator
        run: |
          sed -i -e 's/ONLY_ACTIVE_ARCH = NO;/ONLY_ACTIVE_ARCH = YES;/g' ./ios/MaestroCache.xcodeproj/project.pbxproj
          npx react-native run-ios --simulator="iPhone 14 Pro (16.4)" --mode=Release

      - name: See what we have in DerviedData
        run: |
          cd "~/Library/Developer/Xcode/DerivedData"
          ls

      - name: run Maestro
        run: maestro test ./maestro/test.yaml
        continue-on-error: true
