name: checking-if-we-ccache-correct

on: push

jobs:
  check-correct-ccache:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

    steps:
      - name: Run xcode-select
        run: sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: see the output of the command
        run: xcrun simctl list devices | grep -E "iPhone 14 Pro \(.*\)" | head -n 1 | cut -d '(' -f 2 | cut -d ')' -f 1

      - name: See Simulators list
        run: open -a Simulator --args -CurrentDeviceUDID $(xcrun simctl list devices | grep -E "iPhone 14 Pro \(.*\)" | head -n 1 | cut -d '(' -f 2 | cut -d ')' -f 1)

      - name: see if the simulator is open
        run: xcrun simctl list devices booted
