name: checking-if-we-ccache-correct

on: push

jobs:
  check-correct-ccache:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

    steps:
      - name: Run xcode-select
        run: sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: See Simulators list
        run: xcrun simctl list devices | grep -e "iPhone 14 Pro (.*)" | cut -d '(' -f 2 | cut -d ')' -f 1 | read SIMULATOR_ID ; echo "$SIMULATOR_ID"
  
