name: Build iOS

on: push

jobs:
  build:
    name: Build iOS Example App
    runs-on: macos-14
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v2
        continue-on-error: true

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.
          bundler-cache: true

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            examples/basic/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: cd ios && pod install
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build App
        run: |
          set -o pipefail && xcodebuild \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace MaestroCache.xcworkspace \
          -scheme MaestroCache \
          -sdk iphonesimulator \
          -configuration Release \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty

      
