name: Trying M1 machine

on: push

jobs:
  test-m1:
    runs-on: macos-14
    steps:
      - name: Hello World
        run: echo "Hello World"
      - name: Runner Info
        run: system_profiler SPSoftwareDataType SPHardwareDataType
